### ISSUE TITLE
setup-apim.sh 만들기

### ISSUE THREAD

**Issue by justinyoo** [devrel-kr/nhn-toast-notification-service-custom-connector#25]
애플리케이션을 셋업하는 전체 프로세스는 아래와 같습니다.

1. `main.bicep`을 이용해서 Azure API Management와 Azure Functions 앱을 생성합니다.
2. Azure CLI의 `az functionapp deploy ...` 명령어를 이용해서 앱을 배포합니다.
3. `provision-apiManagementApi.bicep`을 이용해서 배포한 펑션앱과 API Management 앱을 연결시킵니다.

현재 지민님께서 완성하신 부분은 1번이구요, 이제 setup-apim.sh 파일을 생성하셔서 2번과 3번을 완성시키세요.

이 때, 2번을 수행하면서 필요한 아티팩트는 깃헙 API를 이용해서 최신 버전의 릴리즈를 찾아야 합니다. 그리고 그렇게 찾은 아티팩트의 URL을 이용해 배포하세요.

3번을 수행하면서는 `az deployment group create ...` 명령어를 이용해 URL을 지정해서 수행하게 하세요. 이 때 bicep 파일을 직접 활용할 수 없기 때문에 `provision-apiManagementApi.bicep` 파일을 `provision-apiManagementApi.json` 파일로 변환해야 합니다. 이미 이 부분은 리포지토리에 변환되어 있으니 그 파일을 활용하는 것으로 해서 진행하세요.

질문 있으시면 디스코드에 남겨주세요!

**Comment by justinyoo** [comment]
혹시 bash 스크립트를 만들 때 필요한 loop 활용하는 예제입니다: https://ryanstutorials.net/bash-scripting-tutorial/bash-loops.php

**Comment by wlals761** [comment]
https://docs.github.com/en/rest/actions/artifacts#about-the-artifacts-api의 예시 코드를 보고 curl -H "Accept: application/vnd.github.v3+json" \
https://api.github.com/repos/devrel-kr/nhn-toast-notification-service-custom-connector/actions/artifacts 을 하여 SmsVerificationApp의 archive_download_url 을  확인했습니다. 

그리고 https://docs.microsoft.com/ko-kr/cli/azure/functionapp?view=azure-cli-latest#az-functionapp-deploy의 예시 코드를 보고 배포 테스트를 해보기 위해 az functionapp deploy --resource-group rg-nt-pjm-krc --name fncapp-nt-sms-verify-pjm-krc --src-url https://api.github.com/repos/devrel-kr/nhn-toast-notification-service-custom-connector/actions/artifacts/227931676/zip --type zip 을 해보고 뒤에 --async true 옵션도 붙여보고 해봤지만 
Zip deployment failed 이 뜨며 계속 에러가 발생합니다.

위의 과정 중 어디서 잘못한건지 알수있을까요

**Comment by justinyoo** [comment]
요거 참조해 보세요: https://github.com/devkimchi/APIM-OpenAPI-Sample/blob/main/Resources/setup-apim.sh
