### ISSUE TITLE
workflow_call 파일에 펑션 앱을 배열로 받고 이를 활용하기

### ISSUE THREAD

**Issue by justinyoo** [devrel-kr/nhn-toast-notification-service-custom-connector#26]
https://github.com/devrel-kr/nhn-toast-notification-service-custom-connector/blob/e8d5b94ae2b06a799bc5bd54cec7d2c6ed0b94ab/.github/workflows/release-azure.yaml#L9-L16

위 코드 스니펫을 보면 SMS와 SMS Verification 을 하드코딩해 두었습니다. 이걸 workflow_call 로 보낼 때 변수로 보내서 배열로 처리하게 할 수 있을까요? 그러면 앞으로 몇 개의 앱이 더 추가가 된다고 하더라도 최초 배열값만 수정하면 그 다음부터는 알아서 자동으로 될 것 같아요.

아니면 이걸 매트릭스로 처리할 수도 있을 것 같은데요, 그렇게 하면 배포 workflow_call 은 한번에 앱 하나만 배포하지만 matrix 로 루프 돌리면 원하는 숫자만큼 돌릴 수도 있을 것 같습니다.

**Comment by KIMTHE** [comment]
![image](https://user-images.githubusercontent.com/29460783/166143214-67e9d7e3-93ff-405c-a48a-047db9a6aefd.png)

- 현재 workflow를 수정중인데, azure로 배포를 시도하니 해당 리소스그룹을 찾을수없다고 나옵니다.
- 해당 사진에는 Sms.Verification 을 azure로 배포하는 bash script 수행결과입니다. 

![image](https://user-images.githubusercontent.com/29460783/166144070-0cac5c06-a602-4506-abfd-85ec2f877496.png)
- 리소스 그룹 내의 함수 앱 이름과 매치가 되지않아서 오류가 뜬것을 확인했습니다.

![image](https://user-images.githubusercontent.com/29460783/166144128-6d91c950-77a5-48d1-9cd6-7945df50ddc2.png)
- 다음과 같이 폴더명으로 함수 앱 이름도 같게 설정하기 때문에, 리소스 그룹 내의 함수 앱 이름을 수정하면 에러가 해결될 것 같습니다.
- 혹시 함수앱을 만들때 bicep으로 이름을 'sms-verify' 으로 하는건가요?

**Comment by KIMTHE** [comment]
![image](https://user-images.githubusercontent.com/29460783/166147101-a35b512b-6144-484d-b0df-0ec5c3a24d17.png)

![image](https://user-images.githubusercontent.com/29460783/166147131-10084cf0-4d24-47ad-b9d1-c7b6bc206dba.png)

- 다음과 같이 폴더명과 이름이 매칭되도록 함수앱을 azure portal에서 만들어서 수행해본결과, github action으로 배포를 성공하였습니다.
- PR완료했습니다! #27

**Comment by justinyoo** [comment]
애저 펑션 앱 이름은 `fncapp-nt-sms-dev-krc`와 `fncapp-nt-sms-verify-dev-krc`의 이름으로 가는 게 맞구요, 소스 코드의 프로젝트 폴더명은 `NhnToast.Sms`, `NhnToast.Sms.Verification`이 맞습니다.

애저 리소스의 네이밍 컨벤션과 소스코드의 네이밍 컨벤션은 서로 관련은 있지만 같지 않아요. 따라서, 애저 펑션 앱의 이름을 바꾸는 것은 허용되지 않습니다.

**Comment by KIMTHE** [comment]
> 애저 펑션 앱 이름은 `fncapp-nt-sms-dev-krc`와 `fncapp-nt-sms-verify-dev-krc`의 이름으로 가는 게 맞구요, 소스 코드의 프로젝트 폴더명은 `NhnToast.Sms`, `NhnToast.Sms.Verification`이 맞습니다.
> 
> 애저 리소스의 네이밍 컨벤션과 소스코드의 네이밍 컨벤션은 서로 관련은 있지만 같지 않아요. 따라서, 애저 펑션 앱의 이름을 바꾸는 것은 허용되지 않습니다.

넵. [fromjson](https://docs.github.com/en/actions/learn-github-actions/expressions#fromjson)을 이용하여 소스폴더명과 애저리소스명을 json형태로 같이 입력하도록 테스트, 커밋 완료하였습니다.
