### ISSUE TITLE
Request URL builder 만들어 보기

### ISSUE THREAD

**Issue by justinyoo** [devrel-kr/nhn-toast-notification-service-custom-connector#36]
현재 Request URL 을 만드는 과정이 꽤 복잡합니다. 이를 리팩토링해 봅시다.

**현재**:

```csharp
            var baseUrl = this._settings.BaseUrl;
            var version = this._settings.Version;
            var endpoint = this._settings.Endpoints.GetMessage;
            var options = new GetMessageRequestUrlOptions()
            {
                Version = version,
                AppKey = headers.AppKey,
                RequestId = requestId,
                RecipientSeq = int.TryParse(req.Query["recipientSeq"].ToString(), out int recipientSeqVal) ? recipientSeqVal : 0,
            };
            var requestUrl = this._settings.Formatter.Format($"{baseUrl.TrimEnd('/')}/{endpoint.TrimStart('/')}", options);
```

**향후**:

```csharp
var requestUrl = new RequestUrlBuilder().WithSettings(settings).WithHeaders(headers).WithQueries(queries).Build();
```

추가로 RequestURL Builder 에 해당하는 단위테스트 역시도 함께 만들어야 합니다.

힌트:
1. `RequestUrlBuilder` 클라스를 만들고 그 안에 `WithSettings(...)`, `WithHeaders(...)`, `WithQueries(...)`, `Build()` 메소드를 추가합니다.
2. DSL 형태의 Chained Method 를 활용해 봅니다.
3. Chained Method 를 위해서는 Extension Method 형식을 고려해 볼 수도 있습니다.

**Comment by dltmddn** [comment]
현재 네임 스페이스 종속성 문제 때문에 NhnToast.Sms에 Builder 이름으로 새 폴더에 작업 중입니다.
RequestUrlOptions 처럼 RequestUrlBulder를 만들고 이를 상속받아서 4가지 trigger에 해당하는 방식으로 작업 했습니다.

문제점
1. name space 종속성 문제 해결을 위해 Generic 형식에 들어가는 SmsEndpointSetting을 추상화 할 방법을 찾지 못했습니다.
2. 4가지 트리거에 Endpoint들이 다르기 때문에 하나의 RequestUrlBuilder로 처리가 가능한지 잘 모르겠습니다.
호출하는 트리거가 어떤 것인지 확인하는 방법이 있을까요?

궁금한 것
2번 문제점을 해결하지 못해서 상속 받는 구조로 만들다 보니 Extension Method를 활용해야 하는 필요성을 아직 모르겠습니다.

**Comment by justinyoo** [comment]
필요하다면 과감하게 `RequestUrlOptions` 개체를 버려야 할 수도 있습니다.

혹시 코드 리뷰를 위해 PR을 날리고 거기서 논의를 이어가도 될까요?

**Comment by dltmddn** [comment]
현재까지 진행 내용 PR했습니다.

**Comment by dltmddn** [comment]
멘토님 WithQueries(queries)에서 queries를 역직렬화 해서 받은 딕셔너리를 이용해서 
최종 request URL을 만들 때 endpoint에서 key/{key} 형식에서 {key} 부분을 key를 이용해 value로 치환하려 하는데
기존의 RequestQueries들의 멤버들이 API의 이름과 대 소문자 차이가 있거나 조금씩 이름이 다른 상황입니다.
RequestQueries에서 멤버들을 JSONPROPERTY로 매칭 해주면 해결 될 것 같은데 변경해도 될까요?
