### ISSUE TITLE
APIM에 CORS 정책 추가하기

### ISSUE THREAD

**Issue by justinyoo** [devrel-kr/nhn-toast-notification-service-custom-connector#69]
아래 두 URL을 APIM의 CORS 정책에 추가하기

* https://make.powerapps.com
* https://make.powerautomate.com

**Comment by bewisesh91** [comment]
승현, 호준 이슈 해결 진행해보겠습니다.

**Comment by justinyoo** [comment]
리드미 파일에 있는 Deploy to Azure 버튼을 실제로 클릭해서 전체 애플리케이션을 한 번 설치해 보시면 좋겠습니다. 그러면 좀 더 이해가 쉬울 거예요. 혹시 필요하시면 따로 시간 한 번 잡아서 데모를 보시지요

**Comment by minusmo** [comment]
멘토님 **APIManagement cross domain policy docs**를 확인하고 생각해보았는데요, **apim-global-policy.xml** 에 **<allowed-origins>** 태그안에 **<origin>** 태그를 추가하면 될 것같다는 생각이 들었습니다. 맞는지 궁금합니다!!

**Comment by justinyoo** [comment]
맞습니다! 그리고 한 군데가 더 있어요. bicep 파일 중에서 storage account 쪽도 한 번 확인해 보세욥.

**Comment by bewisesh91** [comment]
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/70636283/184534528-50436eca-928e-43fc-8052-89c22004313c.png">
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/70636283/184534535-12024ccf-0e8c-4b95-a9f4-11b02583078b.png">
이렇게 두 부분에 추가를 하면 될 것 같습니다! 
확인 해주시면 수정하도록 하겠습니다 :)

**Comment by justinyoo** [comment]
맞습니다! 그리고 추가하시는 김에 australia.flow.microsoft.com 도 함께 추가해 주세욥! (알파벳 순서)

실제로 추가하신 후에 Deploy to Azure 버튼을 클릭해서 만들어진 리소스에 제대로 들어가는지도 확인해 보셔야 합니다!

**Comment by minusmo** [comment]
멘토님!! 저희가 일단 PR 만들기는 했는데, Deploy to Azure 버튼 링크가 현재 **업스트림**으로 잡혀있어서 **포크한 리포지토리에서 Deploy to Azure 버튼을 클릭**해서는 **수정된 CORS가 APIM global policy에 들어가는 것**을 확인할 수 없는 것 같습니다. 아마 **CLI**로 직접 배포 명령을 내리거나 포크된 리포지토리의 링크로 **버튼 링크를 수정해서** 누르면 **CORS Policy**가 잘 추가된 것을 확인할 수 있으리라 생각됩니다.

**Comment by justinyoo** [comment]
README.md 파일의 링크를 포크한 리포지토리로 수정하시면 됩니다. 그리고 bicep 이랑 셸 스크립트 부분에 있는 링크들 역시도 거기에 맞춰 수정하시면 됩니다! 그리고 한 번 해 보신 후에 잘 되면 다시 원래대로 돌려놓으면 되겠죠?

**Comment by minusmo** [comment]
배포 테스트는 승현님이 포크한 리포지토리를 제가 다시 포크한 리포지토리에서 소스코드를 수정해서 진행했습니다.

제가 지금 배포 돌려놓은게 많아서 _deployment script error(resource conflict)_가 발생해서 **provisioning**은 제대로 확인할 수가 없는데,
생성된 apim의 global cors policy 와 storageAccount 의 cors policy에는 추가된 url이 있는 것을 확인할 수 있었습니다.

provisioning은 생성된 제 리소스 그룹 완전 삭제 후 확인하거나 다른 분 계정으로 확인해야 할 것 같습니다.
![스크린샷 2022-08-18 오후 7 49 46](https://user-images.githubusercontent.com/19248098/185378372-3a4c9add-40d1-490b-a55a-4cee2422a759.png)
![스크린샷 2022-08-18 오후 7 51 21](https://user-images.githubusercontent.com/19248098/185378387-27220e97-3a07-4523-a86b-43a4e785731e.png)
.

**Comment by minusmo** [comment]
멘토님 말씀대로 모든 리소스 그룹 클리어링하고, Purge-ApiManagement.ps1 으로 모든 soft-deleted api-management 리소스 삭제하는 작업을 했습니다.
그리고 main.bicep, azuredeploy.bicep을 리빌드 하고 배포하니까 모든 프로세스가 정상적으로 작동하네요. 
Swagger 에도 apim을 통해 문제없이 등록됩니다!
머지해도 문제없을 것 같습니다!!

몇개의 증명 스크린 샷을 첨부합니다.
![스크린샷 2022-08-18 오후 10 27 57](https://user-images.githubusercontent.com/19248098/185410906-9c4857fe-d3c8-4da8-b9d7-efeb98410d23.png)

![스크린샷 2022-08-18 오후 10 28 11](https://user-images.githubusercontent.com/19248098/185410989-c603ab29-374e-4853-a011-a4f0c4572193.png)

![스크린샷 2022-08-18 오후 10 28 36](https://user-images.githubusercontent.com/19248098/185411053-bbe6d610-8d1e-4083-a400-2aa34c515667.png)

![스크린샷 2022-08-18 오후 10 38 23](https://user-images.githubusercontent.com/19248098/185411089-2884d9b8-e5d7-45e0-9360-fa0095e06318.png)

![스크린샷 2022-08-18 오후 10 38 46](https://user-images.githubusercontent.com/19248098/185411146-afb558d9-d7ae-4bc2-9b94-689032fded0c.png)

**Comment by justinyoo** [comment]
좊습니다!
