### ISSUE TITLE
Validator 클라스 안의 Regex 의존성 수정하기

### ISSUE THREAD

**Issue by justinyoo** [devrel-kr/nhn-toast-notification-service-custom-connector#70]
Validator 클라스 안쪽에 들여다 보면 어떤 것들은 Regex 개체가 있습니다. 이 개체 의존성을 역전시켜야 합니다. 혹은 적어도 싱글톤으로 작동할 수 있게끔 해야 합니다.

**Comment by justinyoo** [comment]
* 참조: https://github.com/FluentValidation/FluentValidation/issues/472

**Comment by justinyoo** [comment]
* 참조: https://docs.fluentvalidation.net/en/latest/di.html

**Comment by MultiDCP** [comment]
상민, 현승, 서희 한 팀으로 해당 이슈 해결해보도록 하겠습니다.

**Comment by MultiDCP** [comment]
멘토님에게 질문이 있습니다!
```C#
private bool IsValidDateFormat(string date)
{
    if (date == null)
    {
        return false;
    }
    else
    {
        return Regex.IsMatch(date, @"^([0-9][0-9][0-9][0-9])-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[0-1]) ([01][0-9]|2[0123]):([0-5][0-9]):([0-5][0-9])$");
    }
}
```
저희 조가 이해하기로는 현재 프로젝트에서는 각 코드들에서 다음과 같은 IsValidDateFormat 메소드를 호출할 때(예를 들어, ListMessagesRequestQueryValidator 클래스의 메소드를 사용하는 상황일 때) bool 값을 리턴해주기 위해서 정규식 개체의 IsMatch 메소드를 불러와 정규식이 일치하는지를 확인하는 것으로 알고 있습니다.
하지만 현재로써는 이 정규식 개체가 호출될 때마다 이미 만들어져 있는 하나의 객체를 참조하는 것이 아니라 매번 새롭게 정규식라는 객체가 생성되어 구조상으로 좋지 못하고, 이를 해결하기 위해 해당 정규식 객체를 싱글톤으로 전체 실행 중 단 한 번만 실행될 수 있도록 고치는 것이 저희가 해결해야 하는 이슈가 맞으며 저희가 제대로 이해하고 있는 것인지를 확인받고 싶습니다.

또한, 현재 저희가 고민하고 있는 방식은 이 정규식의 생성자와 메소드 등을 싱글톤으로써 관할하는 클래스를 새롭게 만드는 것인데, 이 클래스를 만들 때 각 Validator 코드들에 클래스로 각각 넣어주는 것이 좋은지, 아니면 정규식 클래스만을 담당하는(IsMatch와 같은 메소드를 또 불러올 수 있는) 새로운 CS 코드를 작성하여 모든 코드에서 참조해오는 것이 좋은지 조언을 구하고 싶습니다.

답변해주실 수 있다면 진심으로 감사드리겠습니다!

**Comment by justinyoo** [comment]
> 저희 조가 이해하기로는 현재 프로젝트에서는 각 코드들에서 다음과 같은 IsValidDateFormat 메소드를 호출할 때(예를 들어, ListMessagesRequestQueryValidator 클래스의 메소드를 사용하는 상황일 때) bool 값을 리턴해주기 위해서 정규식 개체의 IsMatch 메소드를 불러와 정규식이 일치하는지를 확인하는 것으로 알고 있습니다. 하지만 현재로써는 이 정규식 개체가 호출될 때마다 이미 만들어져 있는 하나의 객체를 참조하는 것이 아니라 매번 새롭게 정규식라는 객체가 생성되어 구조상으로 좋지 못하고, 이를 해결하기 위해 해당 정규식 객체를 싱글톤으로 전체 실행 중 단 한 번만 실행될 수 있도록 고치는 것이 저희가 해결해야 하는 이슈가 맞으며 저희가 제대로 이해하고 있는 것인지를 확인받고 싶습니다.
> 

제대로 이해하셨습니다!

> 또한, 현재 저희가 고민하고 있는 방식은 이 정규식의 생성자와 메소드 등을 싱글톤으로써 관할하는 클래스를 새롭게 만드는 것인데, 이 클래스를 만들 때 각 Validator 코드들에 클래스로 각각 넣어주는 것이 좋은지, 아니면 정규식 클래스만을 담당하는(IsMatch와 같은 메소드를 또 불러올 수 있는) 새로운 CS 코드를 작성하여 모든 코드에서 참조해오는 것이 좋은지 조언을 구하고 싶습니다.
> 

아마도 `RegexWrapper` 같은 클라스를 만들어서 그걸 싱글톤으로 생성한 후 이 wrapper 클라스를 validator의 생성자에 파라미터로 의존성 주입하는 방법이 될 것 같은데요? 굳이 wrapper 클라스를 만드는 이유는 아래와 같은 수도 코드 같은 형태가 되지 않을까 싶습니다.

```csharp
public interface IRegexDateTimeWrapper
{
    bool IsMatch(string date);
}

public class RegexDateTimeWrapper : IRegexDateTimeWrapper
{
    private static Regex regex = new Regex("pattern");

    public bool IsMatch(string date)
    {
        // Logic goes here
    }
}
```
